In [118]:
import pandas as pd

In [119]:
df = pd.read_csv('spotify_millsongdata.csv')

In [120]:
df.head(5)

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [121]:
df.tail(5)

,artist,song,link,text
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [122]:
# Checking the shape of the DataFrame
df.shape

(57650, 4)

In [123]:
# Checking for null values in the DataFrame
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [124]:
# Dropping the 'link' column and resetting the index
df = df.sample(5000).drop('link', axis=1).reset_index(drop=True)

In [147]:
df.tail(10)

,artist,song,text
4990,Lil Wayne,Colorful Clothes,oknowshawtihairyellowshawtieyebrownshawtosogol...
4991,Natalie Cole,Christmas Waltz,"frostwindowpane,candlgleaminsidpaintcandicaneo..."
4992,Ed Sheeran,Firefly,ifellinlovenexttoyouburnfireinthiroomitjustfit...
4993,Zebrahead,Someday,"lateoutthedoor,grabmyclothoffthefloor,backpack..."
4994,Genesis,Feeding The Fire,youareterrifibythesmallestsoundbecausyouliveyo...
4995,Human League,Darkness,"wheremydreamarealltoocleardark,darkfillwithall..."
4996,Tragically Hip,You're Everywhere,"youareeverywher,withinandwithoutwhereitdon'tma..."
4997,Mariah Carey,Hero,there'saheroifyoulookinsidyourheartyoudon'thav...
4998,Fastball,'Til I Get It Right,wellispentallmymoneyattherecordstoreboughtacop...
4999,Green Day,Blitzkrieg Bop,heyho!letgo!heyho!letgo!heyho!letgo!heyho!letg...

In [127]:
# Viewing the first text entry in the DataFrame
df['text'][0]

'I\'m as fake as e wedding cake  \r\nAnd I\'m Vague and I know that I\'m homopolitan  \r\nPitifully predictable  \r\nCorrectly political  \r\n  \r\nI\'m the new, I\'m the new, new model  \r\nI\'ve got nothing inside  \r\nBetter in the head and in bed  \r\nAt the office  \r\nI can suck and I smile  \r\nNew, new, new model  \r\n  \r\nI can choke and diet on coke  \r\nI\'m Spun and I know  \r\nThat I\'m Stoned and Rolling  \r\n  \r\nLifelike and poseable  \r\nHopeless and disposable  \r\n  \r\nI\'m the new, I\'m the new, new model  \r\nI\'ve got nothing inside  \r\nBetter in the head and in bed  \r\nAt the office  \r\nI can suck and I smile  \r\nNew, new, new model  \r\n  \r\nDon\'t let them know how far you go  \r\nOr that you use you "lovers"  \r\nOh look, you\'re like a vcr  \r\nStick something in to know  \r\nJust who you are you  \r\n  \r\nNew, new, new model\r\n\r\n'

In [128]:
df.shape

(5000, 3)

### Text Preprocessing

In [129]:
# Cleaning the 'text' column by converting to lowercase, replacing non-word characters and newlines with spaces
df['text'] = df['text'].str.lower().replace(r'^\w\s', ' ').replace(r'\n', ' ', regex=True)

In [143]:
df.tail(5)

,artist,song,text
4995,Human League,Darkness,"wheremydreamarealltoocleardark,darkfillwithall..."
4996,Tragically Hip,You're Everywhere,"youareeverywher,withinandwithoutwhereitdon'tma..."
4997,Mariah Carey,Hero,there'saheroifyoulookinsidyourheartyoudon'thav...
4998,Fastball,'Til I Get It Right,wellispentallmymoneyattherecordstoreboughtacop...
4999,Green Day,Blitzkrieg Bop,heyho!letgo!heyho!letgo!heyho!letgo!heyho!letg...

In [130]:
import nltk
from nltk.stem.porter import PorterStemmer

stemmer = PorterStemmer()

# Tokenize and stem the text
def tokenize(text):
    tokens = nltk.word_tokenize(text)
    stemming = [stemmer.stem(ch) for ch in tokens]
    return ''.join(stemming)

In [131]:
# Applying the tokenize function to the 'text' column of the DataFrame
df['text'] = df['text'].apply(lambda x: tokenize(x))

In [132]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [133]:
tfidvec = TfidfVectorizer(analyzer='word', stop_words='english')
matrix = tfidvec.fit_transform(df['text'])
similarity = cosine_similarity(matrix)

In [134]:
similarity[0]

array([1., 0., 0., ..., 0., 0., 0.])

In [ ]:
# Function to recommend songs based on the input song
df[df['song'] == 'Darkness']

,artist,song,text
4995,Human League,Darkness,"wheremydreamarealltoocleardark,darkfillwithall..."

In [ ]:
# Recommender Function
def recommend(song_name):
    # Finding the index of the song in the DataFrame
    idx = df[df['song'] == song_name].index[0]
    dist = sorted(list(enumerate(similarity[idx])), reverse=True, key=lambda x: x[1])

    songs = []

    # Getting the top 20 similar songs based on cosine similarity
    for i in dist[1:21]:
        # Appending the song names to the list of recommended songs
        songs.append(df.iloc[i[0]].song)
    return songs

In [ ]:
# Recommending songs similar to 'Darkness'
recommend('Darkness')

["Don't",
 "Small Y'all",
 'Enlightenment',
 "Don't Worry, Kyoko",
 'Evil Woman',
 "Don't Cha",
 "Small Y'all",
 "Don't Be Careless Love",
 'Conehead',
 'Thunder',
 "Don't Ever Let It End",
 "Don't Forget About Us",
 'Driftwood',
 'Doing Fine',
 "Don't Call Me White",
 "Don't Say Goodnight (It's Time For Love)",
 'Village Man',
 "Don't You Know",
 'Changes',
 "Don't Let Go"]

In [146]:
import pickle
pickle.dump(similarity, open('similarity.pkl', 'wb'))
pickle.dump(df, open('df.pkl', 'wb'))